import { useCallback,useEffect,useMemo,useRef,useState } from 'react';
import { BarChart3,CheckSquare,Clock3,LayoutDashboard,Settings,ShieldCheck,Sun,Moon,Timer,AlertCircle } from 'lucide-react';
import { dashboard as loadDashboard,request,safeMessage,sessions as loadSessions,tasks as loadTasks } from './api';
import { hourInput,isoDay,localDayStartIso,sessionCsv } from './format';
import { accentText } from './accent';
import { timerStep } from './timerMath';
import { FocusPage,type Draft } from './pages/FocusPage';
import { DashboardPage } from './pages/DashboardPage';
import { ReportPage,type Criteria } from './pages/ReportPage';
import { TasksPage } from './pages/TasksPage';
import { SettingsPage } from './pages/SettingsPage';
import { SessionDialog } from './components/SessionDialog';
import { RetroactiveDialog } from './components/RetroactiveDialog';
import { Dialog } from './components/Dialog';
import type { Color,Dashboard,Session,Task,TimerNotice } from './types';
import type { CSSProperties } from 'react';

type Page='focus'|'dashboard'|'reports'|'tasks'|'settings';
const blank:Draft={client:'',project:'',activity:'',details:'',consultant:'',cardReference:'',hourlyRate:'',category:'Normal',mode:'Cronômetro',minutes:25};
const nav:{id:Page;label:string;icon:typeof Clock3}[]=[{id:'focus',label:'Apontar horas',icon:Clock3},{id:'dashboard',label:'Dashboard',icon:LayoutDashboard},{id:'reports',label:'Relatórios',icon:BarChart3},{id:'tasks',label:'Tarefas',icon:CheckSquare},{id:'settings',label:'Configurações',icon:Settings}];
export function App(){
 const [page,setPage]=useState<Page>('focus'),[sessions,setSessions]=useState<Session[]>([]),[allSessions,setAllSessions]=useState<Session[]>([]),[taskRows,setTaskRows]=useState<Task[]>([]),[dashboardData,setDashboard]=useState<Dashboard|null>(null),[clientColors,setClientColors]=useState<Color[]>([]),[quickPresets,setQuickPresets]=useState([25,50,90]),[quickLimit,setQuickLimit]=useState(5),[quickFavorites,setQuickFavorites]=useState<string[]>([]),[defaultRate,setDefaultRate]=useState(''),[draft,setDraft]=useState(blank),[active,setActive]=useState<Session|null>(null),[elapsed,setElapsed]=useState(0),[showValues,setShowValues]=useState(false),[theme,setTheme]=useState('system'),[accent,setAccent]=useState('#0070F2'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[editing,setEditing]=useState<Session|null>(null),[deleting,setDeleting]=useState<Session|null>(null),[retroactiveOpen,setRetroactiveOpen]=useState(false),[finishOpen,setFinishOpen]=useState(false),[pendingTask,setPendingTask]=useState<Task|null>(null);
 const refresh=useCallback(async()=>{try{const [history,taskList,settings,colors]=await Promise.all([loadSessions(),loadTasks(),request<Record<string,string>>('/api/settings'),request<Color[]>('/api/settings/colors')]);setSessions(history);setAllSessions(history);setTaskRows(taskList);setClientColors(colors);setShowValues(settings.showValues==='true');setTheme(settings.theme||'system');setAccent(settings.accent||'#0070F2');setQuickPresets((settings['quick.presets']||'25,50,90').split(',').map(Number).filter(v=>v>=1&&v<=999));const maxProjects=Number(settings['quick.limit']);setQuickLimit([0,5,10,20].includes(maxProjects)?maxProjects:5);setQuickFavorites((settings['quick.favorites']||'').split('\n').filter(Boolean));const rate=Number(settings['pricing.defaultHourlyRate']);setDefaultRate(Number.isFinite(rate)&&rate>0?rate.toLocaleString('pt-BR',{maximumFractionDigits:2}):'');setActive(history.find(s=>s.status==='Em andamento'||s.status==='Pausada')||null);const current=history.find(s=>s.status==='Em andamento'||s.status==='Pausada');setElapsed(current?.focusSeconds||0);}catch(e){setError(safeMessage(e));}},[]);
 useEffect(()=>{void refresh();},[refresh]);
 const startedAt=useRef(performance.now()),lastSaved=useRef(0);
 useEffect(()=>{if(!active||active.status!=='Em andamento')return;startedAt.current=performance.now();lastSaved.current=elapsed;const timer=window.setInterval(()=>{const step=timerStep(lastSaved.current,startedAt.current,performance.now());setElapsed(step.total);if(step.shouldSave){lastSaved.current=step.saved;startedAt.current=step.startedAt;void request(`/api/sessions/${active.id}/tick`,'POST',{focusSeconds:step.total}).catch(e=>setError(safeMessage(e)));}},250);return()=>window.clearInterval(timer);},[active?.id,active?.status]);
 useEffect(()=>{document.documentElement.dataset.theme=theme;document.documentElement.style.setProperty('--accent',accent);document.documentElement.style.setProperty('--accent-text',accentText(accent));},[theme,accent]);
 useEffect(()=>{const state:TimerNotice={elapsed,running:active?.status==='Em andamento',activity:active?.activity||draft.activity};window.foco.updateTimer(state);},[elapsed,active,draft.activity]);
 const call=async<T,>(path:string,method='POST',body?:unknown)=>request<T>(path,method,body);
 const saveSessionDraft=async(input:Draft,task:Task|null=null)=>{const now=new Date().toISOString();const configuredRate=task?.hourlyRate??hourInput(input.hourlyRate||defaultRate);const created=await call<Session>('/api/sessions','POST',{taskId:task?.id||null,client:task?.client||input.client,project:task?.project||input.project,activity:task?.activity||input.activity,details:task?.details||input.details,consultant:task?.consultant||input.consultant,cardReference:task?.cardReference||input.cardReference,startAt:now,endAt:null,plannedSeconds:input.mode==='Timer'?input.minutes*60:0,hourlyRate:configuredRate,status:'Em andamento',category:input.category});setActive(created);setElapsed(0);setPendingTask(null);setPage('focus');};
 const start=async()=>{setError('');try{if(active){setPendingTask(null);setFinishOpen(true);return;}await saveSessionDraft(draft);}catch(e){setError(safeMessage(e));}};
 const finish=async(status:'Concluída'|'Encerrada'|'Interrompida')=>{if(!active)return;setBusy(true);try{await call(`/api/sessions/${active.id}/finish`,'POST',{status,focusSeconds:elapsed});setActive(null);setElapsed(0);setFinishOpen(false);await refresh();if(pendingTask)await saveSessionDraft(blank,pendingTask);}catch(e){setError(safeMessage(e));}finally{setBusy(false);}};
 useEffect(()=>{if(active?.status==='Em andamento'&&active.plannedSeconds>0&&elapsed>=active.plannedSeconds)void finish('Concluída');},[active?.id,active?.status,active?.plannedSeconds,elapsed]);
 const toggle=async()=>{try{if(!active){await start();return;}const path=`/api/sessions/${active.id}/${active.status==='Em andamento'?'pause':'resume'}`;const updated=await call<Session>(path,'POST',active.status==='Em andamento'?{focusSeconds:elapsed}:undefined);setActive(updated);}catch(e){setError(safeMessage(e));}};
 useEffect(()=>{const pages:Record<string,Page>={f:'focus',d:'dashboard',r:'reports',t:'tasks',c:'settings'};const handler=(event:KeyboardEvent)=>{if(!event.altKey||event.ctrlKey||event.metaKey)return;const key=event.key.toLowerCase();if(pages[key]){event.preventDefault();setPage(pages[key]);}else if(key==='i'){event.preventDefault();void toggle();}else if(key==='e'&&active){event.preventDefault();setFinishOpen(true);}};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler);},[active,toggle]);
 const historyFilter=async(criteria:Criteria)=>{try{const rows=await loadSessions(criteria as unknown as Record<string,string|number|boolean>);setSessions(rows);}catch(e){setError(safeMessage(e));}};
 const refreshDash=useCallback(async(criteria:Record<string,string>)=>{try{const range={...criteria,from:criteria.from?localDayStartIso(criteria.from):'',to:criteria.to?localDayStartIso(criteria.to,1):''};setDashboard(await loadDashboard(range));}catch(e){setError(safeMessage(e));}},[]);
 const exportCsv=async(rows:Session[])=>{try{await window.foco.saveCsv(`foco-${isoDay(new Date())}.csv`,sessionCsv(rows,showValues));}catch(e){setError(safeMessage(e));}};
 const batch=async(rows:Session[],field:string,value:string)=>{try{await Promise.all(rows.map(s=>request(`/api/sessions/${s.id}`,'PUT',{...s,[field]:value})));await refresh();}catch(e){setError(safeMessage(e));}};
 const toggleFavorite=async(key:string)=>{const next=quickFavorites.includes(key)?quickFavorites.filter(v=>v!==key):[...quickFavorites,key];try{await request('/api/settings','PUT',{'quick.favorites':next.join('\n')});setQuickFavorites(next);}catch(e){setError(safeMessage(e));}};
 const saveTask=async(task:Task|null,value:Record<string,string>)=>{const body={...value,hourlyRate:hourInput(value.hourlyRate),dueDate:value.dueDate||null};await request(task?`/api/tasks/${task.id}`:'/api/tasks',task?'PUT':'POST',body);await refresh();};
 const startTask=(task:Task)=>{if(active){setPendingTask(task);setFinishOpen(true);return;}void saveSessionDraft(blank,task).catch(e=>setError(safeMessage(e)));};
 const colors=useMemo(()=>({accent}),[accent]);
 const deleteSession=async()=>{if(!deleting)return;setBusy(true);try{await request(`/api/sessions/${deleting.id}`,'DELETE');setDeleting(null);await refresh();setDashboard(null);}catch(e){setError(safeMessage(e));}finally{setBusy(false);}};
 return <div className="app-shell" style={colors as CSSProperties}>
   <aside className="sidebar"><div className="brand"><span className="brand__mark"><Timer size={20}/></span><span>foco<small>GEST�O DE TEMPO</small></span></div><div className="sidebar__caption">ESPAÇO DE TRABALHO</div><nav>{nav.map(item=><button key={item.id} className={`nav-item ${page===item.id?'is-active':''}`} onClick={()=>setPage(item.id)}><item.icon size={18}/><span>{item.label}</span>{page===item.id&&<i/>}</button>)}</nav><div className="sidebar__bottom"><span className="local-badge"><ShieldCheck size={14}/> Dados locais</span><small>Foco Desktop · Java Edition</small></div></aside>
   <main className="main-area"><header className="topbar"><div className="breadcrumb">Workspace <span>/</span> {nav.find(n=>n.id===page)?.label}</div><div className="topbar__actions"><button className="icon-button" title="Tema claro" onClick={()=>setTheme(theme==='dark'?'light':'dark')}>{theme==='dark'?<Sun size={18}/>:<Moon size={18}/>}</button><button className="button button--quiet" onClick={()=>window.foco.hideWindow()}>Ocultar na bandeja</button><span className="avatar">M</span></div></header>
    {error&&<div className="toast" role="alert"><AlertCircle size={17}/>{error}<button onClick={()=>setError('')} aria-label="Fechar aviso">×</button></div>}
    {page==='focus'&&<FocusPage draft={draft} setDraft={setDraft} session={active} elapsed={elapsed} running={active?.status==='Em andamento'} showValues={showValues} onToggle={()=>void toggle()} onFinish={()=>setFinishOpen(true)} onOverlay={()=>window.foco.showOverlay()} onRetroactive={()=>setRetroactiveOpen(true)} history={allSessions} tasks={taskRows} colors={clientColors} quickPresets={quickPresets} favoriteKeys={quickFavorites} quickLimit={quickLimit} defaultRate={defaultRate} onToggleFavorite={toggleFavorite}/>}
    {page==='dashboard'&&<DashboardPage data={dashboardData} colors={clientColors} showValues={showValues} onRefresh={refreshDash}/>}
    {page==='reports'&&<ReportPage items={sessions} colors={clientColors} showValues={showValues} onRefresh={historyFilter} onEdit={setEditing} onDelete={setDeleting} onBatch={batch} onExport={exportCsv}/>}
    {page==='tasks'&&<TasksPage items={taskRows} history={allSessions} colors={clientColors} showValues={showValues} onSave={saveTask} onStart={startTask} onComplete={task=>void request(`/api/tasks/${task.id}/complete`,'POST',{completed:!task.completed}).then(refresh).catch(e=>setError(safeMessage(e)))}/>}
    {page==='settings'&&<SettingsPage theme={theme} accent={accent} showValues={showValues} onImported={refresh} onColorsChanged={refresh} onChange={async values=>{try{await request('/api/settings','PUT',values);await refresh();}catch(e){setError(safeMessage(e));}}}/>}
   </main>
   {finishOpen&&<Dialog title="Encerrar apontamento" onClose={()=>{setFinishOpen(false);setPendingTask(null);}}><p>Escolha como registrar o tempo de foco desta sessão.</p>{pendingTask&&<p className="message">Ao concluir, será iniciada a tarefa <strong>{pendingTask.activity}</strong>.</p>}<div className="finish-options">{(['Concluída','Encerrada','Interrompida'] as const).map((status,i)=><button key={status} className={`button ${i===0?'button--primary':''}`} disabled={busy} onClick={()=>void finish(status)}>{status}</button>)}</div></Dialog>}
   {editing&&<SessionDialog session={editing} colors={clientColors} showValues={showValues} onClose={()=>setEditing(null)} onSave={async value=>{await request(`/api/sessions/${editing.id}`,'PUT',value);setEditing(null);await refresh();}}/>}
   {deleting&&<Dialog title="Excluir lançamento" onClose={()=>setDeleting(null)}><p>Excluir definitivamente o lançamento <strong>{deleting.activity}</strong> de {new Date(deleting.startAt).toLocaleString('pt-BR')}?</p><p>As horas e o valor sairão dos relatórios, do dashboard e dos totais da tarefa vinculada.</p><div className="dialog__footer"><button className="button" onClick={()=>setDeleting(null)}>Cancelar</button><button className="button button--danger" disabled={busy} onClick={()=>void deleteSession()}>Excluir lançamento</button></div></Dialog>}
   {retroactiveOpen&&<RetroactiveDialog initial={draft} history={allSessions} tasks={taskRows} colors={clientColors} defaultRate={defaultRate} showValues={showValues} onClose={()=>setRetroactiveOpen(false)} onSave={async value=>{await request('/api/sessions/retroactive','POST',value);setRetroactiveOpen(false);await refresh();}}/>}
  </div>;
}
