import { ProjectColorSeeds } from './components/ClientMarker';
import { availableCatalogs,isArchived } from './organization';
import './organization.css';
import { GapReviewDialog } from './components/GapReviewDialog';
import { QuickCaptureDialog } from './components/QuickCaptureDialog';
import { ReminderCenter } from './components/ReminderCenter';
import { useCallback,useEffect,useMemo,useRef,useState } from 'react';
import { BarChart3,CalendarDays,Clock3,Database,LayoutDashboard,Settings,ShieldCheck,Sun,Moon,Timer,AlertCircle,Plus } from 'lucide-react';
import { dashboard as loadDashboard,request,safeMessage,sessions as loadSessions,tasks as loadTasks,workHours as loadWorkHours } from './api';
import { hourInput,isoDay,localDayStartIso,sessionCsv } from './format';
import { accentText } from './accent';
import { timerStep } from './timerMath';
import { FocusPage,type Draft } from './pages/FocusPage';
import { DashboardPage } from './pages/DashboardPage';
import { ReportPage,type Criteria } from './pages/ReportPage';
import { WorkHoursPage } from './pages/WorkHoursPage';
import { TodayPage } from './pages/TodayPage';
import { TasksPage } from './pages/TasksPage';
import { SettingsPage } from './pages/SettingsPage';
import { CatalogsPage } from './pages/CatalogsPage';
import { SessionDialog } from './components/SessionDialog';
import { RetroactiveDialog } from './components/RetroactiveDialog';
import type { RetroactivePreset } from './components/RetroactiveDialog';
import { NextActionField } from './components/NextActionField';
import { clearDraft } from './components/DraftRecovery';
import { Dialog } from './components/Dialog';
import type { Catalogs,Color,Dashboard,Session,Task,TimerNotice,WorkHoursReport } from './types';
import type { CSSProperties } from 'react';

type Page='today'|'focus'|'dashboard'|'reports'|'work-hours'|'catalogs'|'settings';
const blank:Draft={client:'',project:'',activity:'',details:'',consultant:'',cardReference:'',hourlyRate:'',category:'Normal',mode:'Cronômetro',minutes:25};
const nav:{id:Page;label:string;icon:typeof Clock3}[]=[{id:'today',label:'Tarefas e hoje',icon:Sun},{id:'focus',label:'Apontar horas',icon:Clock3},{id:'dashboard',label:'Dashboard',icon:LayoutDashboard},{id:'reports',label:'Relatórios',icon:BarChart3},{id:'work-hours',label:'Jornada',icon:CalendarDays},{id:'catalogs',label:'Cadastros',icon:Database},{id:'settings',label:'Configurações',icon:Settings}];
export function App(){
 const [workHours,setWorkHours]=useState<WorkHoursReport>({days:[],undefinedPeriods:[]});
 const [page,setPage]=useState<Page>('today'),[sessions,setSessions]=useState<Session[]>([]),[allSessions,setAllSessions]=useState<Session[]>([]),[taskRows,setTaskRows]=useState<Task[]>([]),[catalogs,setCatalogs]=useState<Catalogs>({items:{clients:[],projects:[],activities:[]},possibleDuplicates:[]}),[dashboardData,setDashboard]=useState<Dashboard|null>(null),[clientColors,setClientColors]=useState<Color[]>([]),[quickPresets,setQuickPresets]=useState([25,50,90]),[quickLimit,setQuickLimit]=useState(5),[quickFavorites,setQuickFavorites]=useState<string[]>([]),[defaultRate,setDefaultRate]=useState(''),[draft,setDraft]=useState(blank),[active,setActive]=useState<Session|null>(null),[elapsed,setElapsed]=useState(0),[showValues,setShowValues]=useState(false),[theme,setTheme]=useState('system'),[accent,setAccent]=useState('#0070F2'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[editing,setEditing]=useState<Session|null>(null),[deleting,setDeleting]=useState<Session|null>(null),[retroactiveOpen,setRetroactiveOpen]=useState(false),[retroactivePreset,setRetroactivePreset]=useState<RetroactivePreset|null>(null),[finishOpen,setFinishOpen]=useState(false);
 const [priorityLimit,setPriorityLimit]=useState(5);
 const [dueDefault,setDueDefault]=useState('empty'),[pendingTask,setPendingTask]=useState<Task|null>(null),[nextAction,setNextAction]=useState<string|undefined>();
 const [todayView,setTodayView]=useState<{tab:string;version:number;day?:string}>({tab:'today',version:0});
 const [quickCaptureOpen,setQuickCaptureOpen]=useState(false);
 const [captureVersion,setCaptureVersion]=useState(0);
 const previousPage=useRef(page);
 useEffect(()=>{if(previousPage.current===page)return;previousPage.current=page;const heading=document.querySelector<HTMLElement>('.page-content h1');if(heading){heading.tabIndex=-1;heading.focus({preventScroll:true});}},[page]);
 useEffect(()=>{const navigate=(value:import('./types').TodayNavigation)=>{if(value.tab==='inbox')setQuickCaptureOpen(true);else{setTodayView(current=>({tab:value.tab,day:value.day,version:current.version+1}));setPage('today');}};const off=window.foco.onNavigateToday?.(value=>{navigate(value);void window.foco.takeNavigation?.();});void window.foco.takeNavigation?.().then(value=>{if(value)navigate(value);});return()=>off?.();},[]);
 const capture=()=>{setTodayView(v=>({tab:'inbox',version:v.version+1}));setPage('today');};
 const [journeyDay,setJourneyDay]=useState<string>();
 const [reviewGaps,setReviewGaps]=useState<WorkHoursReport['undefinedPeriods']|null>(null);
 const journeyRange=useRef({from:isoDay(new Date()),to:isoDay(new Date())});
 const reportCriteria=useRef<Criteria|null>(null);
 const refresh=useCallback(async()=>{try{const [history,taskList,settings,colors,catalogData]=await Promise.all([loadSessions(),loadTasks(),request<Record<string,string>>('/api/settings'),request<Color[]>('/api/settings/colors'),request<Catalogs>('/api/catalogs')]);setSessions(reportCriteria.current?await loadSessions(reportCriteria.current):history);setAllSessions(history);setTaskRows(taskList);setClientColors(colors);setCatalogs(catalogData);setPriorityLimit(Number(settings['planning.priorityLimit'])||5);setDueDefault(settings['tasks.defaultDueDate']||'empty');setShowValues(settings.showValues==='true');setTheme(settings.theme||'system');setAccent(settings.accent||'#0070F2');setQuickPresets((settings['quick.presets']||'25,50,90').split(',').map(Number).filter(v=>v>=1&&v<=999));const maxProjects=Number(settings['quick.limit']);setQuickLimit([0,5,10,20].includes(maxProjects)?maxProjects:5);setQuickFavorites((settings['quick.favorites']||'').split('\n').filter(Boolean));const rate=Number(settings['pricing.defaultHourlyRate']);setDefaultRate(Number.isFinite(rate)&&rate>0?rate.toLocaleString('pt-BR',{maximumFractionDigits:2}):'');setActive(history.find(s=>s.status==='Em andamento'||s.status==='Pausada')||null);const current=history.find(s=>s.status==='Em andamento'||s.status==='Pausada');setElapsed(current?.focusSeconds||0);}catch(e){setError(safeMessage(e));}},[]);
 useEffect(()=>{void refresh();},[refresh]);
 const availableTasks=taskRows.filter(t=>!isArchived(t)),activeCatalogs=availableCatalogs(catalogs);
 const startedAt=useRef(performance.now()),lastSaved=useRef(0);
 useEffect(()=>{if(!active||active.status!=='Em andamento')return;startedAt.current=performance.now();lastSaved.current=elapsed;const timer=window.setInterval(()=>{if(switchingTask.current)return;const step=timerStep(lastSaved.current,startedAt.current,performance.now());setElapsed(step.total);if(step.shouldSave){lastSaved.current=step.saved;startedAt.current=step.startedAt;void request(`/api/sessions/${active.id}/tick`,'POST',{focusSeconds:step.total}).catch(e=>setError(safeMessage(e)));}},250);return()=>window.clearInterval(timer);},[active?.id,active?.status]);
 useEffect(()=>{document.documentElement.dataset.theme=theme;document.documentElement.style.setProperty('--accent',accent);document.documentElement.style.setProperty('--accent-text',accentText(accent));},[theme,accent]);
 useEffect(()=>{const state:TimerNotice={elapsed,running:active?.status==='Em andamento',activity:active?.activity||draft.activity};window.foco.updateTimer(state);},[elapsed,active,draft.activity]);
 const call=async<T,>(path:string,method='POST',body?:unknown)=>request<T>(path,method,body);
 const saveSessionDraft=async(input:Draft,task:Task|null=null,switchActive=false,action?:string)=>{const now=new Date().toISOString();const configuredRate=task?.hourlyRate??hourInput(input.hourlyRate||defaultRate);const next={taskId:task?.id||null,client:task?.client||input.client,project:task?.project||input.project,activity:task?.activity||input.activity,details:task?.details||input.details,consultant:task?.consultant||input.consultant,cardReference:task?.cardReference||input.cardReference,startAt:now,endAt:null,plannedSeconds:input.mode==='Timer'?input.minutes*60:0,hourlyRate:configuredRate,status:'Em andamento',category:input.category};const created=await call<Session>(switchActive&&active?'/api/sessions/switch':'/api/sessions','POST',switchActive&&active?{previousId:active.id,focusSeconds:elapsed,next,nextAction:action}:next);setActive(created);if(!task)clearDraft('focus');setElapsed(0);setPage('focus');};
 const start=async()=>{setError('');try{if(active){setFinishOpen(true);return;}await saveSessionDraft(draft);}catch(e){setError(safeMessage(e));}};
 const finish=async(status:'Concluída'|'Encerrada'|'Interrompida',action?:string)=>{if(!active)return;setBusy(true);try{await call(`/api/sessions/${active.id}/finish`,'POST',{status,focusSeconds:elapsed,nextAction:active.taskId?action:undefined});if(active.taskId)clearDraft(`next-action.${active.taskId}`);setActive(null);setElapsed(0);setFinishOpen(false);setPendingTask(null);setNextAction(undefined);await refresh();}catch(e){setError(safeMessage(e));}finally{setBusy(false);}};
 useEffect(()=>{if(!busy&&active?.status==='Em andamento'&&active.plannedSeconds>0&&elapsed>=active.plannedSeconds)void finish('Concluída');},[active?.id,active?.status,active?.plannedSeconds,elapsed]);
 const toggle=async()=>{try{if(!active){await start();return;}const path=`/api/sessions/${active.id}/${active.status==='Em andamento'?'pause':'resume'}`;const updated=await call<Session>(path,'POST',active.status==='Em andamento'?{focusSeconds:elapsed}:undefined);setActive(updated);}catch(e){setError(safeMessage(e));}};
 useEffect(()=>{const pages:Record<string,Page>={h:'today',f:'focus',d:'dashboard',r:'reports',j:'work-hours',t:'today',n:'catalogs',c:'settings'};const handler=(event:KeyboardEvent)=>{if(!event.altKey||event.ctrlKey||event.metaKey||document.querySelector('dialog[open]'))return;const key=event.key.toLowerCase();if(pages[key]){event.preventDefault();if(key==='t'||key==='h')setTodayView(v=>({tab:key==='t'?'tasks':'today',version:v.version+1}));setPage(pages[key]);}else if(key==='q'){event.preventDefault();capture();}else if(key==='i'){event.preventDefault();void toggle();}else if(key==='e'&&active){event.preventDefault();setFinishOpen(true);}};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler);},[active,toggle]);
 const reportVersion=useRef(0);
 const historyFilter=async(criteria:Criteria)=>{const version=++reportVersion.current;try{reportCriteria.current=criteria;const [filtered,history]=await Promise.all([loadSessions(criteria as unknown as Record<string,string|number|boolean>),loadSessions()]);if(version!==reportVersion.current)return false;setSessions(filtered);setAllSessions(history);return true;}catch(e){setError(safeMessage(e));return false;}};
 const journeyVersion=useRef(0);
 const refreshWorkHours=async(range:{from:string;to:string})=>{const version=++journeyVersion.current;try{const report=await loadWorkHours(range);if(version!==journeyVersion.current)return;journeyRange.current=range;setWorkHours(report);}catch(e){setError(safeMessage(e));}};
 const dashboardVersion=useRef(0);
 const refreshDash=useCallback(async(criteria:Record<string,string>)=>{const version=++dashboardVersion.current;try{const range={...criteria,from:criteria.from?localDayStartIso(criteria.from):'',to:criteria.to?localDayStartIso(criteria.to,1):''};const data=await loadDashboard(range);if(version!==dashboardVersion.current)return false;setDashboard(data);return true;}catch(e){setError(safeMessage(e));return false;}},[]);
 const exportCsv=async(rows:Session[],endMode:'real'|'rounded'='real',hoursMode:'real'|'rounded'='rounded')=>{try{await window.foco.saveCsv(`foco-${isoDay(new Date())}.csv`,sessionCsv(rows,showValues,endMode,hoursMode));}catch(e){setError(safeMessage(e));}};
 const exportWorkCsv=async(report=workHours)=>{try{const {workHoursCsv}=await import('./format');await window.foco.saveCsv(`foco-jornada-${isoDay(new Date())}.csv`,workHoursCsv(report));}catch(e){setError(safeMessage(e));}};
 const exportDashboardPdf=async(hideValues:boolean)=>{try{document.body.classList.toggle('pdf-hide-financial',hideValues);await new Promise<void>(resolve=>requestAnimationFrame(()=>resolve()));await window.foco.savePdf(`foco-dashboard-${isoDay(new Date())}.pdf`);}catch(e){setError(safeMessage(e));}finally{document.body.classList.remove('pdf-hide-financial');}};
 const batch=async(rows:Session[],field:string,value:string)=>{try{await Promise.all(rows.map(s=>request(`/api/sessions/${s.id}`,'PUT',{...s,[field]:value})));await refresh();}catch(e){setError(safeMessage(e));}};
 const toggleFavorite=async(key:string)=>{const next=quickFavorites.includes(key)?quickFavorites.filter(v=>v!==key):[...quickFavorites,key];try{await request('/api/settings','PUT',{'quick.favorites':next.join('\n')});setQuickFavorites(next);}catch(e){setError(safeMessage(e));}};
 const saveTask=async(task:Task|null,value:Record<string,string>)=>{const body={...value,hourlyRate:hourInput(value.hourlyRate),dueDate:value.dueDate||null};await request(task?`/api/tasks/${task.id}`:'/api/tasks',task?'PUT':'POST',body);await refresh();};
 const switchingTask=useRef(false);
 const startTask=async(task:Task,confirmed=false)=>{if(active?.taskId&&!confirmed){setNextAction(undefined);setPendingTask(task);return;}if(switchingTask.current||busy)return;switchingTask.current=true;setBusy(true);setError('');try{await saveSessionDraft(blank,task,!!active,confirmed?nextAction:undefined);if(active?.taskId)clearDraft(`next-action.${active.taskId}`);setPendingTask(null);await refresh();}catch(e){setError(safeMessage(e));}finally{switchingTask.current=false;setBusy(false);}};
 const colors=useMemo(()=>({accent}),[accent]);
 const deleteSession=async()=>{if(!deleting)return;setBusy(true);try{await request(`/api/sessions/${deleting.id}`,'DELETE');setDeleting(null);await refresh();setDashboard(null);}catch(e){setError(safeMessage(e));}finally{setBusy(false);}};
 return <ProjectColorSeeds.Provider value={catalogs.projectColorSeeds||{}}><div className="app-shell" style={colors as CSSProperties}>
   <aside className="sidebar"><div className="brand"><span className="brand__mark"><Timer size={20}/></span><span>foco<small>GESTÃO DE TEMPO</small></span></div><div className="sidebar__caption">ESPAÇO DE TRABALHO</div><nav aria-label="Navegação principal">{nav.map(item=><button key={item.id} aria-label={item.label} title={item.label} aria-current={page===item.id?'page':undefined} className={`nav-item ${page===item.id?'is-active':''}`} onClick={()=>setPage(item.id)}><item.icon size={18}/><span>{item.label}</span>{page===item.id&&<i/>}</button>)}</nav><div className="sidebar__bottom"><span className="local-badge"><ShieldCheck size={14}/> Dados locais</span><small>Foco Desktop · Java Edition</small></div></aside>
   <main className="main-area"><header className="topbar"><div className="breadcrumb">Seu espaço <span>/</span> <strong>{nav.find(n=>n.id===page)?.label}</strong></div><div className="topbar__actions"><button className="button" aria-label="Captura rápida" title="Captura rápida (Alt+Q)" onClick={capture}><Plus size={16} aria-hidden="true"/>Captura rápida<kbd className="capture-shortcut" aria-hidden="true">Alt Q</kbd></button><button className="icon-button" aria-label={theme==='dark'?'Ativar tema claro':'Ativar tema escuro'} title={theme==='dark'?'Ativar tema claro':'Ativar tema escuro'} onClick={()=>setTheme(theme==='dark'?'light':'dark')}>{theme==='dark'?<Sun size={18}/>:<Moon size={18}/>}</button><button className="button button--quiet" onClick={()=>window.foco.hideWindow()}>Ocultar na bandeja</button><span className="avatar">M</span></div></header>
    {error&&<div className="toast" role="alert"><AlertCircle size={17}/>{error}<button onClick={()=>setError('')} aria-label="Fechar aviso">×</button></div>}
    <ReminderCenter/>
    <div className="page-content" key={page}>
    {page==='today'&&active&&<div className="message">Apontamento {active.status.toLocaleLowerCase('pt-BR')}: <strong>{active.activity}</strong> <button className="button" onClick={()=>setPage('focus')}>Ver apontamento</button></div>}
    {page==='today'&&<TodayPage taskList={(onPlan,onTasksChanged)=><TasksPage embedded onPlan={onPlan} onChanged={onTasksChanged} defaultDueDate={dueDefault} items={taskRows} history={allSessions} catalogs={catalogs} colors={clientColors} showValues={showValues} onSave={async(task,value)=>{await saveTask(task,value);await onTasksChanged();}} onStart={startTask} onComplete={task=>void request(`/api/tasks/${task.id}/complete`,'POST',{completed:!task.completed}).then(onTasksChanged).catch(e=>setError(safeMessage(e)))} onStatusChange={(task,state)=>void request(`/api/tasks/${task.id}/status`,'POST',{state}).then(onTasksChanged).catch(e=>setError(safeMessage(e)))}/>} priorityLimit={priorityLimit} key={todayView.version} initialTab={todayView.tab} initialDay={todayView.day} captureVersion={captureVersion} tasks={availableTasks} sessions={allSessions} catalogs={activeCatalogs} onChanged={refresh} onStart={startTask} onJourney={day=>{setJourneyDay(day);setPage('work-hours');}}/>}
    {page==='focus'&&<FocusPage draft={draft} setDraft={setDraft} session={active} elapsed={elapsed} running={active?.status==='Em andamento'} showValues={showValues} onToggle={()=>void toggle()} onFinish={()=>setFinishOpen(true)} onOverlay={()=>window.foco.showOverlay()} onRetroactive={()=>{setRetroactivePreset(null);setRetroactiveOpen(true);}} history={allSessions.filter(s=>!catalogs.archivedProjects?.includes(s.project))} tasks={availableTasks} catalogs={activeCatalogs} colors={clientColors} quickPresets={quickPresets} favoriteKeys={quickFavorites} quickLimit={quickLimit} defaultRate={defaultRate} onToggleFavorite={toggleFavorite}/>}
    {page==='dashboard'&&<DashboardPage data={dashboardData} colors={clientColors} showValues={showValues} onRefresh={refreshDash} onExportPdf={hideValues=>void exportDashboardPdf(hideValues)}/>}
    {page==='reports'&&<ReportPage tasks={taskRows} onChanged={refresh} items={sessions} history={allSessions} colors={clientColors} showValues={showValues} onRefresh={historyFilter} onEdit={setEditing} onDelete={setDeleting} onBatch={batch} onExport={exportCsv}/>}
    {page==='work-hours'&&<WorkHoursPage sessions={allSessions} onEdit={setEditing} onReview={setReviewGaps} initialDay={journeyDay} initialUndefined={!!journeyDay} report={workHours} onRefresh={range=>void refreshWorkHours(range)} onExport={report=>void exportWorkCsv(report)} onBook={period=>{const local=(value:string)=>{const date=new Date(value);return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}T${String(date.getHours()).padStart(2,'0')}:${String(date.getMinutes()).padStart(2,'0')}`;};setRetroactivePreset({startAt:local(period.startAt),endAt:local(period.endAt),focusMinutes:Math.floor(period.seconds/60)});setRetroactiveOpen(true);}}/>}
    {page==='catalogs'&&<CatalogsPage catalogs={catalogs} onChanged={refresh}/>}
    {page==='settings'&&<SettingsPage theme={theme} accent={accent} showValues={showValues} clients={catalogs.items.clients} onImported={refresh} onColorsChanged={refresh} onChange={async values=>{try{await request('/api/settings','PUT',values);await refresh();}catch(e){setError(safeMessage(e));}}}/>}
    </div>
   </main>
   {quickCaptureOpen&&<QuickCaptureDialog onClose={()=>setQuickCaptureOpen(false)} onSaved={async()=>{await refresh();setCaptureVersion(version=>version+1);}}/>}
   {finishOpen&&<Dialog title="Encerrar apontamento" onClose={()=>setFinishOpen(false)}><p>Escolha como registrar o tempo de foco desta sessão.</p>{active?.taskId&&<NextActionField key={active.id} taskId={active.taskId} onChange={setNextAction}/>}<div className="finish-options">{(['Concluída','Encerrada','Interrompida'] as const).map((status,i)=><button key={status} className={`button ${i===0?'button--primary':''}`} disabled={busy} onClick={()=>void finish(status,nextAction)}>{status}</button>)}</div></Dialog>}
   {pendingTask&&<Dialog title="Trocar tarefa" onClose={()=>{if(!busy)setPendingTask(null);}}><p>Iniciar {pendingTask.activity} e interromper o apontamento atual.</p>{active?.taskId&&<NextActionField key={active.id} taskId={active.taskId} onChange={setNextAction}/>}<div className="dialog__footer"><button className="button" disabled={busy} onClick={()=>setPendingTask(null)}>Cancelar</button><button className="button button--primary" disabled={busy} onClick={()=>void startTask(pendingTask,true)}>Trocar tarefa</button></div></Dialog>}
   {editing&&<SessionDialog session={editing} history={allSessions} catalogs={catalogs} colors={clientColors} showValues={showValues} onClose={()=>setEditing(null)} onSave={async value=>{await request(`/api/sessions/${editing.id}`,'PUT',value);setEditing(null);await refresh();await refreshWorkHours(journeyRange.current);}}/>}
   {deleting&&<Dialog title="Excluir lançamento" onClose={()=>setDeleting(null)}><p>Excluir definitivamente o lançamento <strong>{deleting.activity}</strong> de {new Date(deleting.startAt).toLocaleString('pt-BR')}?</p><p>As horas e o valor sairão dos relatórios, do dashboard e dos totais da tarefa vinculada.</p><div className="dialog__footer"><button className="button" onClick={()=>setDeleting(null)}>Cancelar</button><button className="button button--danger" disabled={busy} onClick={()=>void deleteSession()}>Excluir lançamento</button></div></Dialog>}
   {reviewGaps&&<GapReviewDialog periods={reviewGaps} initial={blank} history={allSessions} tasks={taskRows} catalogs={catalogs} colors={clientColors} defaultRate={defaultRate} showValues={showValues} onClose={()=>setReviewGaps(null)} onChanged={async()=>{await refresh();await refreshWorkHours(journeyRange.current);}}/>}
   {retroactiveOpen&&<RetroactiveDialog initial={draft} history={allSessions} tasks={taskRows} catalogs={catalogs} colors={clientColors} defaultRate={defaultRate} showValues={showValues} preset={retroactivePreset} onClose={()=>setRetroactiveOpen(false)} onSave={async value=>{await request('/api/sessions/retroactive','POST',value);setRetroactiveOpen(false);setRetroactivePreset(null);await refresh();await refreshWorkHours(journeyRange.current);}}/>}
  </div></ProjectColorSeeds.Provider>;
}
