import { useEffect,useState } from 'react';
import { Card,Field,Empty,Status } from '../components/Field';
import { ClientMarker } from '../components/ClientMarker';
import { localDate,money,duration,amount } from '../format';
import type { Color,Session } from '../types';

export type Criteria={query:string;client:string;project:string;from:string;to:string;activity:string;consultant:string;status:string;category:string;minHours:string;maxHours:string;minValue:string;maxValue:string;sort:string};
const blank:Criteria={query:'',client:'',project:'',from:'',to:'',activity:'',consultant:'',status:'',category:'',minHours:'',maxHours:'',minValue:'',maxValue:'',sort:'recent'};
type Props={items:Session[];colors:Color[];showValues:boolean;onRefresh:(criteria:Criteria)=>void;onEdit:(session:Session)=>void;onDelete:(session:Session)=>void;onBatch:(items:Session[],field:'client'|'project'|'details'|'cardReference',value:string)=>void;onExport:(items:Session[])=>void};
export function ReportPage({items,colors,showValues,onRefresh,onEdit,onDelete,onBatch,onExport}:Props){
  const [criteria,setCriteria]=useState(blank);const [selection,setSelection]=useState<string[]>([]);const [field,setField]=useState<'client'|'project'|'details'|'cardReference'>('client');const [value,setValue]=useState('');
  useEffect(()=>{setSelection([]);},[items]);
  const toggle=(id:string)=>setSelection(s=>s.includes(id)?s.filter(v=>v!==id):[...s,id]);
  return <div className="page-stack"><div className="page-title"><div><h1>Relatório de horas</h1><p>{items.length} sessões · {duration(items.reduce((n,s)=>n+s.focusSeconds,0))}{showValues?` · ${money(items.reduce((n,s)=>n+(amount(s)||0),0))}`:''}</p></div><button className="button" onClick={()=>onExport(selection.length?items.filter(s=>selection.includes(s.id)):items)}>Exportar CSV{selection.length?` (${selection.length})`:''}</button></div>
    <Card title="Filtros do relatório">
      <div className="form-grid form-grid--four"><Field label="Período rápido"><select value="personalizado" onChange={e=>{if(e.target.value==='all')setCriteria(blank);if(e.target.value==='today'){const d=new Date();const next=new Date(d);next.setDate(d.getDate()+1);setCriteria(c=>({...c,from:d.toISOString().slice(0,10),to:next.toISOString().slice(0,10)}));}}}><option value="personalizado">Personalizado</option><option value="today">Hoje</option><option value="all">Todos</option></select></Field>
        <Field label="Data inicial"><input type="date" value={criteria.from} onChange={e=>setCriteria(c=>({...c,from:e.target.value}))}/></Field><Field label="Data final"><input type="date" value={criteria.to} onChange={e=>setCriteria(c=>({...c,to:e.target.value}))}/></Field>
        <Field label="Buscar em todos os campos"><input value={criteria.query} onChange={e=>setCriteria(c=>({...c,query:e.target.value}))}/></Field>
        <Field label="Cliente"><input value={criteria.client} onChange={e=>setCriteria(c=>({...c,client:e.target.value}))}/></Field><Field label="Projeto"><input value={criteria.project} onChange={e=>setCriteria(c=>({...c,project:e.target.value}))}/></Field><Field label="Ordenar"><select value={criteria.sort} onChange={e=>setCriteria(c=>({...c,sort:e.target.value}))}><option value="recent">Mais recentes</option><option value="oldest">Mais antigas</option><option value="focus">Maior foco</option><option value="client">Cliente e projeto</option></select></Field>
      </div>
      <details className="advanced-filters"><summary>Filtros adicionais</summary><div className="form-grid form-grid--four">
        <Field label="Atividade"><input value={criteria.activity} onChange={e=>setCriteria(c=>({...c,activity:e.target.value}))}/></Field><Field label="Consultor"><input value={criteria.consultant} onChange={e=>setCriteria(c=>({...c,consultant:e.target.value}))}/></Field><Field label="Resultado"><select value={criteria.status} onChange={e=>setCriteria(c=>({...c,status:e.target.value}))}><option value="">Todos</option>{['Concluída','Encerrada','Interrompida','Em andamento','Pausada'].map(v=><option key={v}>{v}</option>)}</select></Field><Field label="Categoria"><select value={criteria.category} onChange={e=>setCriteria(c=>({...c,category:e.target.value}))}><option value="">Todas</option><option value="Normal">Normal</option><option value="Agenda">Agenda</option></select></Field>
        <Field label="Horas mínimas"><input type="number" min="0" value={criteria.minHours} onChange={e=>setCriteria(c=>({...c,minHours:e.target.value}))}/></Field><Field label="Horas máximas"><input type="number" min="0" value={criteria.maxHours} onChange={e=>setCriteria(c=>({...c,maxHours:e.target.value}))}/></Field>
        {showValues&&<><Field label="Valor mínimo (R$)"><input type="number" min="0" value={criteria.minValue} onChange={e=>setCriteria(c=>({...c,minValue:e.target.value}))}/></Field><Field label="Valor máximo (R$)"><input type="number" min="0" value={criteria.maxValue} onChange={e=>setCriteria(c=>({...c,maxValue:e.target.value}))}/></Field></>}
      </div></details>
      <div className="actions"><button className="button button--primary" onClick={()=>onRefresh(criteria)}>Atualizar</button><button className="button" onClick={()=>{setCriteria(blank);onRefresh(blank);}}>Limpar filtros</button></div>
    </Card>
    <Card title={`Sessões (${items.length})`} actions={<div className="actions"><button className="button" disabled={selection.length!==1} onClick={()=>{const item=items.find(s=>s.id===selection[0]);if(item)onEdit(item);}}>Editar selecionada</button><button className="button button--danger" disabled={selection.length!==1||items.find(s=>s.id===selection[0])?.status==='Em andamento'||items.find(s=>s.id===selection[0])?.status==='Pausada'} onClick={()=>{const item=items.find(s=>s.id===selection[0]);if(item)onDelete(item);}}>Excluir selecionada</button><button className="button" disabled={!selection.length} onClick={()=>{const chosen=items.filter(s=>selection.includes(s.id));onBatch(chosen,field,value);}}>Aplicar em lote</button></div>}>
      {selection.length>0&&<div className="batch-bar"><span>{selection.length} selecionada(s)</span><select value={field} onChange={e=>setField(e.target.value as typeof field)}><option value="client">Cliente</option><option value="project">Projeto</option><option value="details">Detalhamento</option><option value="cardReference">Card/link</option></select><input aria-label="Novo valor do campo em lote" value={value} onChange={e=>setValue(e.target.value)}/></div>}
      {!items.length?<Empty>Nenhuma sessão encontrada. Ajuste os filtros.</Empty>:<div className="table-scroll"><table><thead><tr><th><input type="checkbox" aria-label="Selecionar todas" checked={items.length>0&&selection.length===items.length} onChange={()=>setSelection(selection.length===items.length?[]:items.map(s=>s.id))}/></th>{['Cliente','Projeto','Consultor','Atividade','Detalhamento','Início','Término','Foco','Categoria',...(showValues?['Valor/hora','Custo']:[]),'Resultado'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{items.map(s=><tr key={s.id}><td><input type="checkbox" aria-label={`Selecionar ${s.activity}`} checked={selection.includes(s.id)} onChange={()=>toggle(s.id)}/></td><td><ClientMarker client={s.client} colors={colors}>{s.client||'Sem cliente'}</ClientMarker></td><td>{s.project||'Sem projeto'}</td><td>{s.consultant||'—'}</td><td>{s.activity}</td><td className="cell-details">{s.details||'—'}</td><td>{localDate(s.startAt)}</td><td>{localDate(s.endAt)}</td><td className="numeric">{duration(s.focusSeconds)}</td><td><span className={`category-badge ${s.category==='Agenda'?'is-agenda':''}`}>{s.category||'Normal'}</span></td>{showValues&&<><td className="numeric">{money(s.hourlyRate)}</td><td className="numeric">{money(amount(s))}</td></>}<td><Status value={s.status}/></td></tr>)}</tbody></table></div>}
    </Card>
  </div>;
}
