import { useEffect,useState } from 'react';
import { Download,FolderInput } from 'lucide-react';
import { Card,Field } from '../components/Field';
import { request } from '../api';
import type { Color } from '../types';
import { hourInput } from '../format';

type Props={theme:string;accent:string;showValues:boolean;onChange:(values:Record<string,string>)=>Promise<void>;onImported:()=>Promise<void>;onColorsChanged:()=>Promise<void>};
export function SettingsPage({theme,accent,showValues,onChange,onImported,onColorsChanged}:Props){
 const [target,setTarget]=useState(''),[backup,setBackup]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[colors,setColors]=useState<Color[]>([]),[colorName,setColorName]=useState(''),[colorHex,setColorHex]=useState('#0070F2'),[presets,setPresets]=useState('25, 50, 90'),[limit,setLimit]=useState('5'),[defaultRate,setDefaultRate]=useState(''),[opacity,setOpacity]=useState('1'),[remember,setRemember]=useState('true'),[noActivate,setNoActivate]=useState('true');
 useEffect(()=>{void request<Color[]>('/api/settings/colors').then(setColors).catch(()=>setColors([]));void request<Record<string,string>>('/api/settings').then(values=>{setTarget(values['backup.destination']||'');setPresets(values['quick.presets']||'25, 50, 90');setLimit(values['quick.limit']||'5');const rate=Number(values['pricing.defaultHourlyRate']);if(Number.isFinite(rate)&&rate>0)setDefaultRate(rate.toLocaleString('pt-BR',{maximumFractionDigits:2}));setOpacity(values['overlay.opacity']||'1');setRemember(values['overlay.remember']||'true');setNoActivate(values['overlay.noActivate']||'true');});},[]);
 const importData=async()=>{const directory=await window.foco.importFolder();if(!directory)return;setBusy(true);setMessage('Validando e importando arquivos V35…');try{const result=await request<{sessions:number;tasks:number;alreadyImported:boolean}>('/api/import/v35','POST',{directory});await onImported();setMessage(result.alreadyImported?'Esta origem já foi importada.':`Importação concluída: ${result.sessions} sessões e ${result.tasks} tarefas.`);}catch(e){setMessage(e instanceof Error?e.message:'Falha na importação.');}finally{setBusy(false);}};
 const configureBackup=async()=>{const directory=await window.foco.chooseFolder();if(!directory)return;setTarget(directory);await onChange({'backup.destination':directory});setMessage('Pasta diária de backup salva. O primeiro backup será criado hoje.');};
 const createBackup=async()=>{setBusy(true);try{const result=await request<{path:string}>('/api/backup','POST',{directory:target,manual:true});setBackup(result.path);setMessage(`Backup criado: ${result.path}`);}catch(e){setMessage(e instanceof Error?e.message:'Escolha a pasta do backup e tente novamente.');}finally{setBusy(false);}};
 const themeChange=(value:string)=>void onChange({theme:value});
 const saveQuick=async()=>{try{const values=presets.split(',').map(v=>Number(v.trim()));if(values.length>8||values.some(v=>!Number.isInteger(v)||v<1||v>999))throw new Error('Informe até oito durações inteiras entre 1 e 999 minutos.');const rate=hourInput(defaultRate);await onChange({'quick.presets':values.join(','),'quick.limit':limit,'pricing.defaultHourlyRate':rate==null?'':String(rate)});setMessage('Preferências de lançamento rápido salvas.');}catch(e){setMessage(e instanceof Error?e.message:'Preferências inválidas.');}};
 const saveColor=async()=>{try{const saved=await request<Color>('/api/settings/colors','PUT',{client:colorName,hex:colorHex});setColors(rows=>[...rows.filter(row=>row.client.toLowerCase()!==saved.client.toLowerCase()),saved].sort((a,b)=>a.client.localeCompare(b.client)));setColorName('');await onColorsChanged();}catch(e){setMessage(e instanceof Error?e.message:'A cor não foi salva.');}};
 const removeColor=async(client:string)=>{try{await request(`/api/settings/colors/${encodeURIComponent(client)}`,'DELETE');setColors(rows=>rows.filter(row=>row.client!==client));await onColorsChanged();}catch(e){setMessage(e instanceof Error?e.message:'A cor não foi removida.');}};
 return <div className="page-stack"><div className="page-title"><div><h1>Configurações</h1><p>Personalize a experiência e proteja seus dados locais.</p></div></div>
  <Card title="Aparência"><div className="form-grid form-grid--three"><Field label="Tema"><select value={theme} onChange={e=>themeChange(e.target.value)}><option value="system">Seguir sistema</option><option value="light">Claro</option><option value="dark">Escuro</option></select></Field><Field label="Cor de destaque"><input type="color" value={accent} onChange={e=>void onChange({accent:e.target.value})}/></Field><label className="check-row"><input type="checkbox" checked={showValues} onChange={e=>void onChange({showValues:String(e.target.checked)})}/> Exibir valores financeiros</label></div></Card>
  <Card title="Lançamento rápido"><div className="form-grid form-grid--three"><Field label="Durações favoritas (minutos, até oito)"><input value={presets} onChange={e=>setPresets(e.target.value)} placeholder="25, 50, 90"/></Field><Field label="Projetos recentes"><select value={limit} onChange={e=>setLimit(e.target.value)}><option value="5">5 projetos</option><option value="10">10 projetos</option><option value="20">20 projetos</option><option value="0">Todos</option></select></Field><Field label="Valor/hora padrão (R$)"><input inputMode="decimal" value={defaultRate} onChange={e=>setDefaultRate(e.target.value)} placeholder="Opcional"/></Field></div><button className="button" onClick={()=>void saveQuick()}>Salvar lançamento rápido</button></Card>
  <Card title="Importação inicial da V35"><p>Selecione a pasta que contém os arquivos XML. Os dados serão validados antes da gravação. Os originais permanecem inalterados.</p><button className="button" disabled={busy} onClick={()=>void importData()}><FolderInput size={16}/> Escolher pasta e importar</button></Card>
  <Card title="Backup automático diário"><p>Cria uma cópia ZIP local com banco SQLite, sessões, tarefas, configurações e dados operacionais. Mantém todas as cópias.</p><div className="actions"><button className="button" onClick={()=>void configureBackup()}> {target||'Escolher pasta de destino'}</button><button className="button button--primary" disabled={busy} onClick={()=>void createBackup()}><Download size={16}/> Criar backup agora</button></div>{backup&&<p className="muted">Último arquivo: {backup}</p>}</Card>
  <Card title="Bandeja e sobreposição"><p>Fechar a janela principal a oculta na bandeja. Use o menu da bandeja ou o painel do apontamento para abrir a sobreposição sempre visível.</p><div className="form-grid form-grid--three"><label className="check-row"><input type="checkbox" checked={remember==='true'} onChange={e=>{const value=String(e.target.checked);setRemember(value);void onChange({'overlay.remember':value});}}/> Lembrar posição</label><Field label={`Opacidade da sobreposição: ${Math.round(Number(opacity)*100)}%`}><input type="range" min="0.4" max="1" step="0.1" value={opacity} onChange={e=>{setOpacity(e.target.value);void onChange({'overlay.opacity':e.target.value});}}/></Field><Field label="Ativação"><select value={noActivate} onChange={e=>{setNoActivate(e.target.value);void onChange({'overlay.noActivate':e.target.value});}}><option value="true">Não roubar foco</option><option value="false">Ativável com foco</option></select></Field></div><button className="button" onClick={()=>window.foco.showOverlay()}>Mostrar sobreposição</button></Card>
  <Card title="Cores dos clientes"><p>Escolha a cor do cliente para gráficos e marcadores nos lançamentos, projetos e tarefas. Clientes sem personalização usam a paleta automática nos gráficos.</p><div className="color-editor"><Field label="Cliente"><input maxLength={200} value={colorName} onChange={e=>setColorName(e.target.value)}/></Field><Field label="Cor"><input type="color" value={colorHex} onChange={e=>setColorHex(e.target.value)}/></Field><button className="button button--primary" disabled={!colorName.trim()} onClick={()=>void saveColor()}>Salvar cor</button></div>{colors.length>0&&<div className="color-list">{colors.map(color=><div key={color.client}><i style={{background:color.hex}}/><span>{color.client}</span><code>{color.hex}</code><button className="button button--quiet" onClick={()=>void removeColor(color.client)}>Remover</button></div>)}</div>}</Card>
  {message&&<p className="message" role="status">{message}</p>}
 </div>;
}
