import { request,safeMessage } from '../api';
import { SavedViews } from '../components/SavedViews';
import { viewFields,viewText,viewChoice,viewDate } from '../savedViews';
import { isArchived,availableCatalogs } from '../organization';
import { ChecklistDialog } from '../components/ChecklistDialog';
import { useViewState,oneOf } from '../viewPreferences';
import { focusSeconds } from '../hoursBasis';
import { DraftRecovery,clearDraft } from '../components/DraftRecovery';
import { useMemo,useState,type FormEvent } from 'react';
import { Card,Empty,Field } from '../components/Field';
import { CatalogSelect } from '../components/CatalogSelect';
import { ClientMarker,ClientColorPreview,ProjectMarker } from '../components/ClientMarker';
import { Dialog } from '../components/Dialog';
import { HistoryDialog } from '../components/HistoryDialog';
import { duration,isoDay,money } from '../format';
import { buildFillSuggestions,valuesFor,type SuggestionField } from '../fillSuggestions';
import type { Catalogs,Color,Session,Task } from '../types';

const blank={client:'',project:'',activity:'',details:'',consultant:'',cardReference:'',hourlyRate:'',dueDate:''};
const newTask=(mode:string)=>({...blank,dueDate:mode==='today'?isoDay(new Date()):''});
type TaskView={query:string;states:string[];sort:'due'|'activity'|'client'|'state';direction:'asc'|'desc';client:string;project:string;activity:string;consultant:string;dueFrom:string;dueTo:string;archive:string;hoursMode:'real'|'rounded'};
const validTaskView=viewFields<TaskView>({query:viewText,states:value=>Array.isArray(value)&&value.length<=4&&value.every(viewChoice('Pendente','Em andamento','Concluída','Aguardando')),sort:viewChoice('due','activity','client','state'),direction:viewChoice('asc','desc'),client:viewText,project:viewText,activity:viewText,consultant:viewText,dueFrom:viewDate,dueTo:viewDate,archive:viewChoice('active','archived','all'),hoursMode:viewChoice('real','rounded')});
type Props={embedded?:boolean;onPlan?:(task:Task)=>void;onChanged?:()=>Promise<void>;defaultDueDate?:string;items:Task[];history:Session[];catalogs:Catalogs;colors:Color[];showValues:boolean;onSave:(task:Task|null,value:typeof blank)=>Promise<void>;onStart:(task:Task)=>void;onComplete:(task:Task)=>void;onStatusChange:(task:Task,state:string)=>void};

export function TasksPage({embedded=false,onPlan,onChanged=async()=>{},defaultDueDate='empty',items,history,catalogs,colors,showValues,onSave,onStart,onComplete,onStatusChange}:Props){
 const [query,setQuery]=useState(''),[states,setStates]=useState<string[]>([]),[sort,setSort]=useViewState('tasks.sort','due',oneOf('due','activity','client','state')),[direction,setDirection]=useViewState('tasks.direction','asc',oneOf('asc','desc')),[client,setClient]=useState(''),[project,setProject]=useState(''),[activity,setActivity]=useState(''),[consultant,setConsultant]=useState(''),[dueFrom,setDueFrom]=useState(''),[dueTo,setDueTo]=useState(''),[editing,setEditing]=useState<Task|null|false>(false),[form,setForm]=useState(blank),[error,setError]=useState(''),[historyTask,setHistoryTask]=useState<Task|null>(null);
 const [archive,setArchive]=useState('active'),[checklistTask,setChecklistTask]=useState<Task|null>(null),[archiveTask,setArchiveTask]=useState<Task|null>(null),[archiveBusy,setArchiveBusy]=useState(false);
 const [hoursMode,setHoursMode]=useViewState('tasks.hours','rounded',oneOf('real','rounded'));
 const taskSeconds=(task:Task)=>hoursMode==='rounded'?task.focusSeconds:(task.realFocusSeconds??history.filter(s=>s.taskId===task.id).reduce((sum,s)=>sum+focusSeconds(s,'real'),0));
 const suggestions=useMemo(()=>buildFillSuggestions(history,items),[history,items]);
 const matches=(value:string,filter:string)=>!filter||value.toLocaleLowerCase('pt-BR').includes(filter.toLocaleLowerCase('pt-BR'));
 const filtered=items.filter(t=>(archive==='all'||(archive==='archived')===isArchived(t))&&(!states.length||states.includes(t.state))&&(!query||[t.activity,t.client,t.project,t.details,t.consultant,t.cardReference].join(' ').toLocaleLowerCase('pt-BR').includes(query.toLocaleLowerCase('pt-BR')))&&matches(t.client,client)&&matches(t.project,project)&&matches(t.activity,activity)&&matches(t.consultant,consultant)&&(!dueFrom||!!t.dueDate&&t.dueDate>=dueFrom)&&(!dueTo||!!t.dueDate&&t.dueDate<=dueTo)).sort((a,b)=>{
 const sign=direction==='asc'?1:-1;
  if(sort==='due'&&Boolean(a.dueDate)!==Boolean(b.dueDate))return a.dueDate?-1:1;
  const dueCompare=a.dueDate&&b.dueDate?a.dueDate.localeCompare(b.dueDate):0;
  const primary=sort==='activity'?a.activity.localeCompare(b.activity,'pt-BR'):
   sort==='client'?`${a.client} ${a.project}`.localeCompare(`${b.client} ${b.project}`,'pt-BR'):
   sort==='state'?(['Pendente','Em andamento','Concluída','Aguardando'].indexOf(a.state)-['Pendente','Em andamento','Concluída','Aguardando'].indexOf(b.state)):dueCompare;
  return (primary?primary*sign:a.activity.localeCompare(b.activity,'pt-BR'))||a.id.localeCompare(b.id);
 });
 const edit=(task:Task|null)=>{setEditing(task);setForm(task?{client:task.client,project:task.project,activity:task.activity,details:task.details,consultant:task.consultant,cardReference:task.cardReference,hourlyRate:task.hourlyRate==null?'':String(task.hourlyRate),dueDate:task.dueDate||''}:newTask(defaultDueDate));setError('');};
 const apply=(field:SuggestionField,value:string)=>setForm(current=>({...current,[field]:value}));
 const list=(field:SuggestionField)=><datalist id={`task-suggestions-${field}`}>{valuesFor(suggestions,field,form[field]).map(value=><option key={value} value={value}/>)}</datalist>;
 const input=(field:SuggestionField,maxLength?:number)=><><input list={`task-suggestions-${field}`} maxLength={maxLength} inputMode={field==='hourlyRate'?'decimal':undefined} value={form[field]} onChange={e=>apply(field,e.target.value)}/>{list(field)}</>;
 const submit=async(event:FormEvent)=>{event.preventDefault();if(!form.activity.trim()){setError('Informe a atividade da tarefa.');return;}if(form.activity.length>200||form.details.length>1000||form.cardReference.length>500){setError('Um campo excede o tamanho máximo permitido.');return;}try{await onSave(editing||null,form);clearDraft(`task.${editing?editing.id:'new'}`);setEditing(false);}catch(e){setError(e instanceof Error?e.message:'Não foi possível salvar.');}};
 return <div className="page-stack"><div className="page-title"><div>{embedded?<h2>Todas as tarefas</h2>:<h1>Tarefas</h1>}<p>Crie tarefas, acumule apontamentos e conclua manualmente.</p></div><button className="button button--primary" onClick={()=>edit(null)}>Nova tarefa</button></div>
  <SavedViews scope="tasks" criteria={{query,states,sort,direction,client,project,activity,consultant,dueFrom,dueTo,archive,hoursMode}} validate={validTaskView} fromKey="dueFrom" toKey="dueTo" defaultPeriod="all" onApply={next=>{setQuery(next.query);setStates(next.states);setSort(next.sort);setDirection(next.direction);setClient(next.client);setProject(next.project);setActivity(next.activity);setConsultant(next.consultant);setDueFrom(next.dueFrom);setDueTo(next.dueTo);setArchive(next.archive);setHoursMode(next.hoursMode);}}/>
  <Field label="Arquivamento"><select value={archive} onChange={e=>setArchive(e.target.value)}><option value="active">Ativas</option><option value="archived">Arquivadas</option><option value="all">Todas</option></select></Field><Field label="Horas exibidas"><select value={hoursMode} onChange={e=>setHoursMode(e.target.value as typeof hoursMode)}><option value="rounded">Arredondadas</option><option value="real">Reais</option></select></Field><p>Totais em horas {hoursMode==='real'?'reais':'arredondadas'}. Registros antigos sem precisão recuperável mantêm o tempo salvo.</p>
  <Card title={`Lista de tarefas (${filtered.length})`}><div className="form-grid form-grid--four"><Field label="Buscar em todos os campos"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Atividade, cliente, detalhamento ou card"/></Field><fieldset className="status-filters"><legend>Estado (selecione vários)</legend>{['Pendente','Em andamento','Concluída','Aguardando'].map(s=><label key={s} className={`status-choice ${states.includes(s)?'is-selected':''}`}><input type="checkbox" checked={states.includes(s)} onChange={()=>setStates(current=>current.includes(s)?current.filter(v=>v!==s):[...current,s])}/>{s}</label>)}<button type="button" className="button button--quiet" disabled={!states.length} onClick={()=>setStates([])}>Limpar estados</button></fieldset><Field label="Ordenar por"><select value={sort} onChange={e=>setSort(e.target.value as typeof sort)}><option value="due">Prazo limite</option><option value="activity">Atividade</option><option value="client">Cliente e projeto</option><option value="state">Estado</option></select></Field><Field label="Direção"><select value={direction} onChange={e=>setDirection(e.target.value as 'asc'|'desc')}><option value="asc">Crescente</option><option value="desc">Decrescente</option></select></Field></div>
   <details className="advanced-filters"><summary>Filtros adicionais</summary><div className="form-grid form-grid--four"><Field label="Cliente"><input value={client} onChange={e=>setClient(e.target.value)}/></Field><Field label="Projeto"><input value={project} onChange={e=>setProject(e.target.value)}/></Field><Field label="Atividade"><input value={activity} onChange={e=>setActivity(e.target.value)}/></Field><Field label="Consultor"><input value={consultant} onChange={e=>setConsultant(e.target.value)}/></Field><Field label="Prazo a partir de"><input type="date" value={dueFrom} onChange={e=>setDueFrom(e.target.value)}/></Field><Field label="Prazo até"><input type="date" value={dueTo} onChange={e=>setDueTo(e.target.value)}/></Field></div></details>
   {!filtered.length?<Empty>Nenhuma tarefa encontrada. Crie uma tarefa ou ajuste a busca.</Empty>:<div className="table-scroll"><table><thead><tr>{['Estado','Atividade','Detalhamento','Prazo','Cliente','Projeto','Consultor','Card/link','Apontamentos','Tempo',...(showValues?['Valor/hora']:[]),'Ações'].map(v=><th key={v}>{v}</th>)}</tr></thead><tbody>{filtered.map(task=><tr key={task.id}><td><select className={`task-state task-state--${task.state==='Concluída'?'done':task.state==='Em andamento'?'active':task.state==='Aguardando'?'waiting':'pending'}`} aria-label={`Estado de ${task.activity}`} value={task.state} onChange={e=>onStatusChange(task,e.target.value)}>{['Pendente','Em andamento','Concluída','Aguardando'].map(state=><option key={state}>{state}</option>)}</select></td><td>{task.activity}{isArchived(task)&&<small> · {task.projectArchived?'Projeto arquivado':'Arquivada'}</small>}</td><td className="cell-details">{task.details||'—'}</td><td>{task.dueDate?new Date(`${task.dueDate}T12:00:00`).toLocaleDateString('pt-BR'):'—'}</td><td><ClientMarker client={task.client} colors={colors}>{task.client||'—'}</ClientMarker></td><td><ProjectMarker client={task.client} project={task.project} colors={colors}/></td><td>{task.consultant||'—'}</td><td><CardLink value={task.cardReference}/></td><td className="numeric">{task.entries}</td><td className="numeric">{duration(taskSeconds(task))}</td>{showValues&&<td className="numeric">{money(task.hourlyRate)}</td>}<td><div className="actions"><button className="button button--quiet" disabled={task.completed||isArchived(task)} onClick={()=>onStart(task)}>Iniciar</button>{onPlan&&<button className="button button--quiet" disabled={isArchived(task)} onClick={()=>onPlan(task)}>Planejar</button>}<button className="button button--quiet" onClick={()=>edit(task)}>Editar</button><button className="button button--quiet" onClick={()=>setHistoryTask(task)}>Histórico</button><button className="button button--quiet" onClick={()=>setChecklistTask(task)}>Checklist ({task.checklistCompleted||0}/{task.checklistTotal||0})</button><button className="button button--quiet" disabled={!!task.projectArchived&&!task.archived} onClick={()=>{setError('');setArchiveTask(task);}}>{task.archived?'Restaurar tarefa':'Arquivar tarefa'}</button><button className="button button--quiet" disabled={task.state==='Em andamento'&&task.entries>0&&task.completed} onClick={()=>onComplete(task)}>{task.completed?'Reabrir':'Concluir'}</button></div></td></tr>)}</tbody></table></div>}
  </Card>
  {editing!==false&&<Dialog title={editing?'Editar tarefa':'Nova tarefa'} onClose={()=>setEditing(false)}><form onSubmit={submit} className="dialog-form"><DraftRecovery key={(editing?editing.id:'new')} id={`task.${(editing?editing.id:'new')}`} value={form} onRecover={setForm}/><p className="muted">As sugestões acompanham o campo digitado e preenchem somente esse campo.</p>
   <div className="form-grid form-grid--two"><CatalogSelect label="Cliente" optional value={form.client} options={catalogs.items.clients} onChange={value=>setForm(f=>({...f,client:value}))} preview={<ClientColorPreview client={form.client} colors={colors}/>}/><CatalogSelect label="Projeto" optional value={form.project} options={[...new Set([...availableCatalogs(catalogs).items.projects,...(editing&&editing.project?[editing.project]:[])])]} onChange={value=>setForm(f=>({...f,project:value}))}/><CatalogSelect label="Atividade *" required value={form.activity} options={catalogs.items.activities} onChange={value=>setForm(f=>({...f,activity:value}))}/><Field label="Prazo limite"><input type="date" value={form.dueDate} onChange={e=>setForm(f=>({...f,dueDate:e.target.value}))}/></Field><Field label="Detalhamento"><textarea maxLength={1000} rows={3} value={form.details} onChange={e=>setForm(f=>({...f,details:e.target.value}))}/></Field><Field label="Consultor solicitante">{input('consultant',200)}</Field><Field label="Card ou link">{input('cardReference',500)}</Field>{showValues&&<Field label="Valor por hora em R$">{input('hourlyRate')}</Field>}</div>
   {error&&<p className="message message--error" role="alert">{error}</p>}<div className="dialog__footer"><button type="button" className="button" onClick={()=>setEditing(false)}>Cancelar</button><button className="button button--primary">Salvar tarefa</button></div>
  </form></Dialog>}
  {error&&editing===false&&!archiveTask&&<p role="alert" className="message message--error">{error}</p>}
  {checklistTask&&<ChecklistDialog task={checklistTask} onClose={()=>setChecklistTask(null)} onChanged={onChanged}/>}
  {archiveTask&&<Dialog title={archiveTask.archived?'Restaurar tarefa':'Arquivar tarefa'} onClose={()=>{if(!archiveBusy)setArchiveTask(null);}}><p>{archiveTask.archived?'Restaurar':'Arquivar'} “{archiveTask.activity}”? Apontamentos, checklist, histórico e data de planejamento serão preservados. A prioridade será removida.{archiveTask.projectArchived?' O projeto também precisa ser restaurado em Cadastros.':''}</p>{error&&<p role="alert">{error}</p>}<div className="dialog__footer"><button className="button" disabled={archiveBusy} onClick={()=>setArchiveTask(null)}>Cancelar</button><button className="button button--primary" disabled={archiveBusy} onClick={async()=>{setArchiveBusy(true);setError('');try{await request(`/api/tasks/${archiveTask.id}/archive`,'PUT',{archived:!archiveTask.archived});await onChanged();setArchiveTask(null);}catch(e){setError(safeMessage(e));}finally{setArchiveBusy(false);}}}>Confirmar {archiveTask.archived?'restauração':'arquivamento'}</button></div></Dialog>}
  {historyTask&&<HistoryDialog entityType="task" entityId={historyTask.id} title={historyTask.activity} onClose={()=>setHistoryTask(null)}/>}
 </div>;
}

function CardLink({value}:{value:string}){
 if(!value)return <>—</>;
 try{const url=new URL(value);if(!['https:','http:'].includes(url.protocol))return <span>{value}</span>;return <a href={url.href} target="_blank" rel="noreferrer">Abrir link</a>;}catch{return <span>{value}</span>;}
}
