import { useMemo,useState,type FormEvent } from 'react';
import { Card,Empty,Field,Status } from '../components/Field';
import { ClientMarker,ClientColorPreview } from '../components/ClientMarker';
import { Dialog } from '../components/Dialog';
import { duration,money } from '../format';
import { buildFillSuggestions,valuesFor,type SuggestionField } from '../fillSuggestions';
import type { Color,Session,Task } from '../types';

const blank={client:'',project:'',activity:'',details:'',consultant:'',cardReference:'',hourlyRate:'',dueDate:''};
type Props={items:Task[];history:Session[];colors:Color[];showValues:boolean;onSave:(task:Task|null,value:typeof blank)=>Promise<void>;onStart:(task:Task)=>void;onComplete:(task:Task)=>void};

export function TasksPage({items,history,colors,showValues,onSave,onStart,onComplete}:Props){
 const [query,setQuery]=useState(''),[state,setState]=useState('Todas'),[dueFrom,setDueFrom]=useState(''),[dueTo,setDueTo]=useState(''),[editing,setEditing]=useState<Task|null|false>(false),[form,setForm]=useState(blank),[error,setError]=useState('');
 const suggestions=useMemo(()=>buildFillSuggestions(history,items),[history,items]);
 const filtered=items.filter(t=>(state==='Todas'||state===t.state)&&(!query||[t.activity,t.client,t.project,t.details,t.consultant,t.cardReference].join(' ').toLocaleLowerCase('pt-BR').includes(query.toLocaleLowerCase('pt-BR')))&&(!dueFrom||!!t.dueDate&&t.dueDate>=dueFrom)&&(!dueTo||!!t.dueDate&&t.dueDate<=dueTo));
 const edit=(task:Task|null)=>{setEditing(task);setForm(task?{client:task.client,project:task.project,activity:task.activity,details:task.details,consultant:task.consultant,cardReference:task.cardReference,hourlyRate:task.hourlyRate==null?'':String(task.hourlyRate),dueDate:task.dueDate||''}:blank);setError('');};
 const apply=(field:SuggestionField,value:string)=>setForm(current=>({...current,[field]:value}));
 const list=(field:SuggestionField)=><datalist id={`task-suggestions-${field}`}>{valuesFor(suggestions,field,form[field]).map(value=><option key={value} value={value}/>)}</datalist>;
 const input=(field:SuggestionField,maxLength?:number)=><><input list={`task-suggestions-${field}`} maxLength={maxLength} inputMode={field==='hourlyRate'?'decimal':undefined} value={form[field]} onChange={e=>apply(field,e.target.value)}/>{list(field)}</>;
 const submit=async(event:FormEvent)=>{event.preventDefault();if(!form.activity.trim()){setError('Informe a atividade da tarefa.');return;}if(form.activity.length>200||form.details.length>1000||form.cardReference.length>500){setError('Um campo excede o tamanho máximo permitido.');return;}try{await onSave(editing||null,form);setEditing(false);}catch(e){setError(e instanceof Error?e.message:'Não foi possível salvar.');}};
 return <div className="page-stack"><div className="page-title"><div><h1>Tarefas</h1><p>Crie tarefas, acumule apontamentos e conclua manualmente.</p></div><button className="button button--primary" onClick={()=>edit(null)}>Nova tarefa</button></div>
  <Card title={`Lista de tarefas (${filtered.length})`}><div className="form-grid form-grid--four"><Field label="Buscar tarefa"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Atividade, cliente, projeto ou card"/></Field><Field label="Estado"><select value={state} onChange={e=>setState(e.target.value)}>{['Todas','Pendente','Em andamento','Concluída'].map(s=><option key={s}>{s}</option>)}</select></Field><Field label="Prazo a partir de"><input type="date" value={dueFrom} onChange={e=>setDueFrom(e.target.value)}/></Field><Field label="Prazo até"><input type="date" value={dueTo} onChange={e=>setDueTo(e.target.value)}/></Field></div>
   {!filtered.length?<Empty>Nenhuma tarefa encontrada. Crie uma tarefa ou ajuste a busca.</Empty>:<div className="table-scroll"><table><thead><tr>{['Estado','Atividade','Prazo','Cliente','Projeto','Consultor','Apontamentos','Tempo',...(showValues?['Valor/hora']:[]),'Ações'].map(v=><th key={v}>{v}</th>)}</tr></thead><tbody>{filtered.map(task=><tr key={task.id}><td><Status value={task.state}/></td><td>{task.activity}</td><td>{task.dueDate?new Date(`${task.dueDate}T12:00:00`).toLocaleDateString('pt-BR'):'—'}</td><td><ClientMarker client={task.client} colors={colors}>{task.client||'—'}</ClientMarker></td><td>{task.project||'—'}</td><td>{task.consultant||'—'}</td><td className="numeric">{task.entries}</td><td className="numeric">{duration(task.focusSeconds)}</td>{showValues&&<td className="numeric">{money(task.hourlyRate)}</td>}<td><div className="actions"><button className="button button--quiet" disabled={task.completed} onClick={()=>onStart(task)}>Iniciar</button><button className="button button--quiet" onClick={()=>edit(task)}>Editar</button><button className="button button--quiet" disabled={task.state==='Em andamento'&&task.entries>0&&task.completed} onClick={()=>onComplete(task)}>{task.completed?'Reabrir':'Concluir'}</button></div></td></tr>)}</tbody></table></div>}
  </Card>
  {editing!==false&&<Dialog title={editing?'Editar tarefa':'Nova tarefa'} onClose={()=>setEditing(false)}><form onSubmit={submit} className="dialog-form"><p className="muted">As sugestões acompanham o campo digitado e preenchem somente esse campo.</p>
   <div className="form-grid form-grid--two"><Field label="Cliente (opcional)">{input('client',200)}<ClientColorPreview client={form.client} colors={colors}/></Field><Field label="Projeto (opcional)">{input('project',200)}</Field><Field label="Atividade *">{input('activity',200)}</Field><Field label="Prazo limite"><input type="date" value={form.dueDate} onChange={e=>setForm(f=>({...f,dueDate:e.target.value}))}/></Field><Field label="Detalhamento"><textarea maxLength={1000} rows={3} value={form.details} onChange={e=>setForm(f=>({...f,details:e.target.value}))}/></Field><Field label="Consultor solicitante">{input('consultant',200)}</Field><Field label="Card ou link">{input('cardReference',500)}</Field>{showValues&&<Field label="Valor por hora em R$">{input('hourlyRate')}</Field>}</div>
   {error&&<p className="message message--error" role="alert">{error}</p>}<div className="dialog__footer"><button type="button" className="button" onClick={()=>setEditing(false)}>Cancelar</button><button className="button button--primary">Salvar tarefa</button></div>
  </form></Dialog>}
 </div>;
}
