import { useRef,useState } from 'react';
import { request,safeMessage } from '../api';
import { Card } from './Field';
import { Dialog } from './Dialog';
type Preview={path:string;sha256:string;counts:Record<string,number>;activeSessions:number;warning:string};
type Result={safetyBackup:string;restoredAt:string};
const names:Record<string,string>={tasks:'Tarefas',sessions:'Apontamentos',task_inbox:'Capturas',settings:'Preferências',change_history:'Histórico de alterações',work_schedule_rules:'Regras de jornada',work_schedule_exceptions:'Exceções de jornada',session_work_intervals:'Intervalos de foco',client_colors:'Cores de clientes',catalog_clients:'Clientes',catalog_projects:'Projetos',catalog_activities:'Atividades',task_plans:'Planejamentos',task_templates:'Modelos de tarefas',daily_reviews:'Revisões diárias',task_estimates:'Estimativas',task_archive:'Tarefas arquivadas',project_archive:'Projetos arquivados',task_checklist:'Etapas de checklist',template_options:'Opções de recorrência'};
export function RestoreBackup({onRestored}:{onRestored:()=>void}){
 const [preview,setPreview]=useState<Preview|null>(null),[busy,setBusy]=useState(false),[confirmed,setConfirmed]=useState(false),[message,setMessage]=useState(''),[result,setResult]=useState<Result|null>(null),saving=useRef(false);
 const choose=async()=>{if(saving.current)return;saving.current=true;setBusy(true);setMessage('');setPreview(null);setConfirmed(false);try{const path=await window.foco.chooseBackup();if(path)setPreview(await request<Preview>('/api/backup/preview','POST',{path}));}catch(e){setMessage(safeMessage(e));}finally{saving.current=false;setBusy(false);}};
 const restore=async()=>{if(!preview||!confirmed||saving.current)return;saving.current=true;setBusy(true);setMessage('');try{setResult(await request<Result>('/api/backup/restore','POST',{path:preview.path,sha256:preview.sha256,confirmed:true}));}catch(e){setMessage(safeMessage(e));setConfirmed(false);}finally{saving.current=false;setBusy(false);}};
 const close=()=>{if(busy)return;if(result){onRestored();return;}setPreview(null);setConfirmed(false);};
 return <Card title="Restaurar backup"><p>Selecione um ZIP criado pelo Foco para conferir seu conteúdo antes de substituir os dados locais. Encerre qualquer apontamento em andamento ou pausado. Uma cópia de segurança será criada antes da restauração.</p><button className="button" disabled={busy} onClick={()=>void choose()}>Escolher backup para conferir</button>{message&&!preview&&<p role="alert" className="message">{message}</p>}
  {preview&&<Dialog title={result?'Backup restaurado':'Conferir restauração'} onClose={close}>{result?<><p>Restauração concluída. Atualize a interface para usar os dados restaurados.</p><p className="restore-path">Cópia anterior: {result.safetyBackup}</p><button className="button button--primary" onClick={onRestored}>Concluir e atualizar Foco</button></>:<><p className="restore-path">Arquivo: {preview.path}</p><p>{preview.warning}</p><div className="table-scroll"><table><thead><tr><th>Conteúdo</th><th>Registros</th></tr></thead><tbody>{Object.entries(preview.counts).map(([key,value])=><tr key={key}><td>{names[key]||key}</td><td>{value}</td></tr>)}</tbody></table></div>{preview.activeSessions>0&&<p className="message">{preview.activeSessions} sessão(ões) aberta(s) no backup voltarão pausadas.</p>}<label className="check-row"><input type="checkbox" checked={confirmed} disabled={busy} onChange={e=>setConfirmed(e.target.checked)}/> Confirmo a substituição dos dados pelo backup conferido.</label>{message&&<p role="alert" className="message">{message}</p>}<div className="dialog__footer"><button className="button" disabled={busy} onClick={close}>Cancelar</button><button className="button button--danger" disabled={busy||!confirmed} onClick={()=>void restore()}>{busy?'Restaurando…':'Restaurar este backup'}</button></div></>}</Dialog>}
 </Card>;
}
