import { useEffect,useRef,useState } from 'react';
import { Card,Field,Status } from './Field';
import { Dialog } from './Dialog';
import { capacitySummary } from './CapacityPanel';
import { request,safeMessage } from '../api';
import { weekDays,shiftDay } from '../calendar';
import { isArchived } from '../organization';
import type { Task } from '../types';
import type { Plan } from '../planning';

export function WeekPlanningPanel({day,onDay,tasks,plans,onMoved}:{day:string;onDay:(day:string)=>void;tasks:Task[];plans:Plan[];onMoved:()=>Promise<void>}){
 const [estimates,setEstimates]=useState<{taskId:string;minutes:number}[]>([]),[capacity,setCapacity]=useState(480),[loaded,setLoaded]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const [moving,setMoving]=useState<Task|null>(null),[target,setTarget]=useState(''),[keepPriority,setKeepPriority]=useState(false),[busy,setBusy]=useState(false);const lock=useRef(false);
 const load=async()=>{setError('');try{const [e,s]=await Promise.all([request<{taskId:string;minutes:number}[]>('/api/planning/estimates'),request<Record<string,string>>('/api/settings')]);setEstimates(Array.isArray(e)?e:[]);setCapacity(Number(s['planning.capacityMinutes']??480));setLoaded(true);}catch(error){setError(safeMessage(error));}};
 useEffect(()=>{void load();},[]);
 const available=tasks.filter(task=>!task.completed&&!isArchived(task)),byId=new Map(plans.map(plan=>[plan.taskId,plan]));
 const days=weekDays(day);
 const open=(task:Task,date=byId.get(task.id)?.plannedDate||day)=>{setMoving(task);setTarget(date);setKeepPriority(false);setError('');setMessage('');};
 const row=(task:Task)=><article className="week-task" key={task.id} draggable={!busy} onDragStart={event=>{event.dataTransfer.setData('application/x-foco-task',task.id);event.dataTransfer.effectAllowed='move';}}><strong>{task.activity}</strong><p>{[task.client,task.project,task.details].filter(Boolean).join(' · ')}</p><Status value={task.state}/>{byId.get(task.id)?.priority? <small>Prioridade {byId.get(task.id)?.priority}</small>:null}{task.dueDate&&<small>Prazo de entrega: {task.dueDate}</small>}<button className="button" disabled={busy} onClick={()=>open(task)} aria-label={`Mover planejamento de ${task.activity} · ${task.id}`}>Mover para outra data</button></article>;
 return <Card title="Planejamento da semana"><div className="actions"><button className="button" onClick={()=>onDay(shiftDay(day,-7))}>Semana anterior</button><strong>{days[0]} a {days[6]}</strong><button className="button" onClick={()=>onDay(shiftDay(day,7))}>Próxima semana</button></div>
  <p>Arraste uma tarefa para um dia e confirme, ou use Mover para outra data pelo teclado. A data de planejamento não altera o prazo de entrega. A prioridade só será preservada se você marcar essa opção.</p>
  {error&&<p role="alert">{error} <button className="button" onClick={()=>void load()}>Recarregar capacidade semanal</button></p>}{message&&<p role="status">{message}</p>}
  <div className="week-grid">{days.map(date=>{const selected=available.filter(task=>byId.get(task.id)?.plannedDate===date),summary=capacitySummary(available,plans,estimates,date);return <section key={date} className="week-day" aria-label={`Planejamento de ${date}`} onDragOver={event=>{event.preventDefault();event.dataTransfer.dropEffect='move';}} onDrop={event=>{event.preventDefault();if(busy)return;const task=available.find(task=>task.id===event.dataTransfer.getData('application/x-foco-task'));if(task)open(task,date);}}><h3>{new Date(`${date}T12:00:00`).toLocaleDateString('pt-BR',{weekday:'long',day:'2-digit',month:'2-digit'})}</h3>{loaded&&<><p>{summary.minutes} min estimados / {capacity} min disponíveis</p>{summary.minutes>capacity&&<p className="message">Sobrecarga: {summary.minutes-capacity} min</p>}{summary.missing>0&&<small>{summary.missing} sem estimativa</small>}</>}{selected.sort((a,b)=>(byId.get(a.id)?.priority||999)-(byId.get(b.id)?.priority||999)||a.activity.localeCompare(b.activity,'pt-BR')).map(row)}{!selected.length&&<p className="muted">Sem tarefas planejadas.</p>}</section>;})}</div>
  <details><summary>Tarefas sem data ({available.filter(task=>!byId.get(task.id)?.plannedDate).length})</summary><div className="week-unplanned">{available.filter(task=>!byId.get(task.id)?.plannedDate).map(row)}</div></details>
  {moving&&<Dialog title="Mover planejamento" onClose={()=>{if(!busy)setMoving(null);}}><form className="dialog-form" onSubmit={event=>{event.preventDefault();if(lock.current)return;lock.current=true;setBusy(true);setError('');void (async()=>{try{await request(`/api/planning/plans/${moving.id}/date`,'PUT',{plannedDate:target||null,keepPriority});setMoving(null);await onMoved();setMessage('Data de planejamento atualizada. Prazo e próxima ação preservados.');}catch(error){setError(safeMessage(error));}finally{lock.current=false;setBusy(false);}})();}}><p>{moving.activity} · prazo de entrega: {moving.dueDate||'sem prazo'}</p><Field label="Nova data de planejamento"><input type="date" value={target} onChange={event=>{setTarget(event.target.value);if(!event.target.value)setKeepPriority(false);}}/></Field><p>Deixe a data vazia para retirar do calendário.</p><label className="check-row"><input type="checkbox" disabled={!target||!byId.get(moving.id)?.priority||moving.state==='Aguardando'} checked={keepPriority} onChange={event=>setKeepPriority(event.target.checked)}/> Preservar prioridade (até três por dia)</label>{error&&<p role="alert">{error}</p>}<div className="dialog__footer"><button type="button" className="button" disabled={busy} onClick={()=>setMoving(null)}>Cancelar movimento</button><button className="button button--primary" disabled={busy}>Confirmar nova data</button></div></form></Dialog>}
 </Card>;
}
